name: dbt CI

on:
  pull_request:
    branches: [main, devs]

jobs:
  dbt-ci:
    runs-on: ubuntu-latest

    env:
      DBT_PROFILES_DIR: .dbt
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-key.json

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt
        run: |
          pip install dbt-bigquery==1.8.0

      - name: Create GCP credentials
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > /tmp/gcp-key.json
          
      - name: Validate GCP key
        run: |
          cat /tmp/gcp-key.json | jq .

      - name: dbt deps
        run: dbt deps

      - name: dbt compile
        run: dbt compile

      - name: dbt run (CI)
        run: dbt run --select tag:ci

      - name: dbt test (CI)
        run: dbt test --select tag:ci
